package com.odev.myestateagencyapi.exception;

public enum ErrorCodes {



  PROPERTY_NOT_FOUND(600),
  PROPERTY_NOT_VALID(601),
  PROPERTY_ALREADY_EXISTS(602),

  AMENITY_NOT_FOUND(610),
  AMENITY_NOT_VALID(611),
  AMENITY_ALREADY_EXISTS(612),

  PROPERTY_STATUS_NOT_FOUND(620),
  PROPERTY_STATUS_NOT_VALID(621),
  PROPERTY_STATUS_ALREADY_EXISTS(622),

  PROPERTY_TYPE_NOT_FOUND(630),
  PROPERTY_TYPE_NOT_VALID(631),
  PROPERTY_TYPE_ALREADY_EXISTS(632),

  BEDROOM_NOT_FOUND(640),
  BEDROOM_NOT_VALID(641),
  BEDROOM_ALREADY_EXISTS(642),

  BATHROOM_NOT_FOUND(650),
  BATHROOM_NOT_VALID(651),
  BATHROOM_ALREADY_EXISTS(652),

  GARAGE_NOT_FOUND(660),
  GARAGE_NOT_VALID(661),
  GARAGE_ALREADY_EXISTS(662),

  CITY_NOT_FOUND(670),
  CITY_NOT_VALID(671),
  CITY_ALREADY_EXISTS(672),

  APP_SETTING_NOT_VALID(661),

  SENDING_EMAIL(700),
  NULL_CLASS_PROPERTY(710),

  ROLE_NOT_FOUND(11000),
  ROLE_NOT_VALID(11001),
  ROLE_ALREADY_EXISTS(12002),

  UTILISATEUR_NOT_FOUND(12000),
  UTILISATEUR_NOT_VALID(12001),
  UTILISATEUR_ALREADY_EXISTS(12002),



  ;

  private final int code;

  ErrorCodes(int code) {
    this.code = code;
  }

  public int getCode() {
    return code;
  }
}
